[package]
name = "mpf-mc-rust"
version = "0.1.0"
authors = ["Jan Kantert <jan-mpf@kantert.net>"]
edition = "2018"

[dependencies]
piston = "0.52.0"
piston2d-graphics = "0.37.0"
pistoncore-glutin_window = "0.66.0"
piston2d-opengl_graphics = "0.74.0"
tonic = "0.3"
prost = "0.6"
tokio = { version = "0.2", features = ["macros"] }

[build-dependencies]
tonic-build = "0.3"